Add cutting grass replay test
Terasology/TestReplayModule pull request #6
Opened 2018-09-28 17:28 UTC by llvieira

### Contains
1. A recording was created using `BuilderSampleGameplay` world generator.
2. One block of grass is cut off.
3. The new `CuttingGrassReplayTest` test class check if the initial block type located in `x:0, y:-1, z:2` is `Grass`, then checks if it is `Air` after the replay. 

### How to test
Running `CuttingGrassReplayTest` class in the headed mode or not, you will get a green bar! :smiley:

2018-10-13 19:14 UTC, iaronaraujo requested changes
I tested both tests on my workspace and it worked perfectly! Well done! The only thing I noticed that seemed "off" was that even though the CuttingGrassAcceptanceTest and CuttingGrassReplayTest have very similar names, they test different things. While the first tests the player position, the second one tests the block position. Therefore, I would suggest renaming CuttingGrassAcceptanceTest to something like "CuttingGrassPlayerLocationAcceptanceTest".

Besides that minor issue, everything else is good! Keep up the good work!

2018-10-17 23:39 UTC, llvieira commented
Thanks for your review, @iaronaraujo. I renamed the test classes to better represent what they really do.

2018-10-17 23:46 UTC, iaronaraujo approved these changes

2018-10-17 23:47 UTC, merged

2018-10-17 23:48 UTC, iaronaraujo commented
With that improved, everything is ready for the merge!